### ISSUE TITLE
Add Colab notebooks with examples 

### ISSUE THREAD

**Issue by mrm8488** [CarperAI/trlx#123]
### 🚀 The feature, motivation, and pitch

How would you see if I create a couple of Colabs with the examples provided?

**Comment by LouisCastricato** [comment]
Sounds good but I think there are issues running then in colab, @reciprocated correct?

**Comment by reciprocated** [comment]
Hi @mrm8488, that would be great!

@LouisCastricato There were few issues back, but I think they are no longer relevant since week ago colab upgraded to 3.8, same version as we use on aws.
- #67 

I think examples can be copied verbatim with some adapting done to batch sizes perhaps
