### ISSUE TITLE
Trying to figure out NLP tasks that trlx can be applied to

### ISSUE THREAD

**Issue by promiseve** [CarperAI/trlx#139]
### 📚 The doc issue

Hi,

Just curious about the range of tasks that trlx supports, I know trl only supports IMDB text continuation tasks. Still, I haven't figured out those supported in trlx apart from the positive review generation tasks. 

Thanks.

### Suggest a potential alternative/fix

Create a section called tasks and explain each.

**Comment by LouisCastricato** [comment]
@Dahoas

**Comment by promiseve** [comment]
Thanks. 
@Dahoas, can I get your discord username on Carper AI?

**Comment by James4Ever0** [comment]
This library is "reward function guided". In order to achieve ChatGPT-level fluency and capability, you need a proper reward function. Details discussed here: #146

**Comment by LouisCastricato** [comment]
Closing issue.
