### ISSUE TITLE
NeoX support

### ISSUE THREAD

**Issue by LouisCastricato** [CarperAI/trlx#14]
We need support for NeoX, EleutherAI's fork of Megatron-Deepspeed. This is already something in active development, just making a GitHub issue for tracking.

**Comment by cat-state** [comment]
TODO:
- [ ] Make IndexedDataset work with RLElements & RolloutStorage
- [ ] Copy-paste ILQL loss & QVModel heads but using GPT2Model from NeoX
- [ ] Copy-paste PPO loss & inferencing

**Comment by LouisCastricato** [comment]
We need to make sure that the top level API remains the same or near the same. I do not know how feasible this is.

**Comment by cat-state** [comment]
> We need to make sure that the top level API remains the same or near the same. I do not know how feasible this is.

Which top level API are you referring to? neox's? or TRLX's?

**Comment by LouisCastricato** [comment]
TRLX's
