### ISSUE TITLE
Use this package for active training for a vision model

### ISSUE THREAD

**Issue by MohamedAliRashad** [CarperAI/trlx#154]
### 🚀 The feature, motivation, and pitch

I am thinking for a method in this package that i give it a text-to-image model that can generate multiple images from a prompt and i show them to the users so they rank them and based on this ranking the model gets updated about what is better images to be produced

### Alternatives

Nothing like this is available i think

**Comment by LouisCastricato** [comment]
@shahbuland is working on stable diffusion support.

**Comment by asmith26** [comment]
Possibly related:
- https://github.com/CarperAI/trlx/issues/20
- https://github.com/CarperAI/trlx/issues/163

**Comment by LouisCastricato** [comment]
Closing issue, as duplicate.
