### ISSUE TITLE
Any thoughts about adding a retrieval mechanism (e.g. RETRO)?

### ISSUE THREAD

**Issue by asmith26** [CarperAI/trlx#155]
### 🚀 The feature, motivation, and pitch

I've come across a similar project, https://github.com/lucidrains/PaLM-rlhf-pytorch, and it quotes on the README:
> Maybe I'll add retrieval functionality too, à la [RETRO](https://github.com/lucidrains/RETRO-pytorch)

From my understanding, a retrieval based model reduces the need for a model to memorize everything, helping to reducing model size, cost,...

Hence I thought it might be useful/interesting to add to this project too.

### Alternatives

- https://github.com/lucidrains/PaLM-rlhf-pytorch
- (related: https://github.com/lucidrains/RETRO-pytorch)

### Additional context

Thanks for all your amazing work! :)

**Comment by LouisCastricato** [comment]
I think it is kind of out of scope of trlx. Perhaps in the future we will consider retrieval. If you want to fork trlx and implement retrieval though, I'd be open to linking to your repository?

**Comment by tholor** [comment]
Could be interesting to combine trlx + [Haystack](https://github.com/deepset-ai/haystack/) for this :thinking: 
If someone is considering a contribution here, feel free to reach out to me. Haystack already supports some retrieval-augmented LMs and we explore options to support training via RLHF.
