### ISSUE TITLE
Implement A2C

### ISSUE THREAD

**Issue by Dahoas** [CarperAI/trlx#16]
Implement additional online RL algorithms

**Comment by ML-Chen** [comment]
Hello, I'd like to be assigned to this issue!

**Comment by geighz** [comment]
Hey @ML-Chen , I am wondering how you are doing, would you like to pair up and tackle this issue?

**Comment by ML-Chen** [comment]
@geighz Would love to sometime later this week! What's your username in the CarperAI Discord server?

**Comment by manavgarg** [comment]
Hey guys, I am interested in this too. Possible to include me here as well?

**Comment by LouisCastricato** [comment]
Is this activate?

**Comment by ML-Chen** [comment]
Working on this now

**Comment by shermansiu** [comment]
Same, collabing with @ML-Chen.

**Comment by shermansiu** [comment]
(I'm Blitz on the Discord)

**Comment by RobertKirk** [comment]
Note that if you have a sufficiently generic implementation of PPO, you have A2C for free: https://github.com/vwxyzjn/a2c_is_a_special_case_of_ppo

**Comment by shermansiu** [comment]
Yes, we're aware of that. It's just a matter of making the configurations nice so that it's easily accessible to end-users. There are also other RL algorithms that can be added.

**Comment by shermansiu** [comment]
(The discussions for this are currently ongoing in the #trlx channel on the CarperAI Discord.)

**Comment by shermansiu** [comment]
https://github.com/CarperAI/trlx/pull/183
