### ISSUE TITLE
wandb.errors.RequireError: require() unsupported requirement: report-editing

### ISSUE THREAD

**Issue by asmith26** [CarperAI/trlx#162]
### 🐛 Describe the bug

Hi there, 

I've successfully ran `python examples/ppo_sentiments.py`, so I though I'd try [Use Ray Tune to launch hyperparameter sweep](https://github.com/CarperAI/trlx#use-ray-tune-to-launch-hyperparameter-sweep) but I'm getting an error I can't seem to fix:

```python
$ python -m trlx.sweep --config configs/sweeps/ppo_sweep.yml examples/ppo_sentiments.py

wandb: WARNING require() unsupported requirement: report-editing
wandb: ERROR Supported wandb.require() features can be found at: https://wandb.me/library-require
Traceback (most recent call last):
  File "~/miniconda3/envs/CarperAI/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "~/miniconda3/envs/CarperAI/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "~/git/CarperAI/trlx/trlx/sweep.py", line 15, in <module>
    from trlx.ray_tune.wandb import log_trials, create_report
  File "~/git/CarperAI/trlx/trlx/ray_tune/wandb.py", line 11, in <module>
    wandb.require("report-editing")
  File "~/miniconda3/envs/CarperAI/lib/python3.10/site-packages/wandb/sdk/wandb_require.py", line 89, in require
    f.apply()
  File "~/miniconda3/envs/CarperAI/lib/python3.10/site-packages/wandb/sdk/wandb_require.py", line 68, in apply
    raise RequireError(last_message)
wandb.errors.RequireError: require() unsupported requirement: report-editing
```

Many thanks for any help! :)

### Which trlX version are you using?

Installing from `main` (i.e. `pip install -e .`

### Additional system and package information

wandb=0.13.7; python=3.10.8; Ubuntu

**Comment by LouisCastricato** [comment]
@ayulockin

**Comment by ayulockin** [comment]
Will make a PR to fix it. Thanks for reporting @asmith26 :)

**Comment by ayulockin** [comment]
Hey @asmith26 can you try to comment out this [line](https://github.com/CarperAI/trlx/blob/8d1bdee94f0c91745268c92771aeb8708f7c56b5/trlx/ray_tune/wandb.py#L10) in case you had cloned the repo and working from it.

**Comment by jon-tow** [comment]
@ayulockin Commenting out that line seems to address the issue + some other updates: https://github.com/jon-tow/trlx/commit/b99c9ce384bcd1e2e7e0cd210c906cc1125fceb0
Here's a PPO sentiment sweep report [here](https://api.wandb.ai/report/carperai/k4xiwpab)
Unfortunately, the automatic report does not seem to be rendering the parallel coordinates plot properly (see [here](https://wandb.ai/carperai/sweep/reports/Hyperparameter-Optimization-Report-main_2023-01-03_20-13-00--VmlldzozMjU4NzY3)). Is this the intended behavior and how it was produced before? Thanks!

**Comment by jon-tow** [comment]
@ayulockin Commenting out the linked line and updating some of the configs seems to have resolved the issue at the following branch: https://github.com/jon-tow/trlx/commit/b99c9ce384bcd1e2e7e0cd210c906cc1125fceb0
* A manual report for the PPO sentiments example, [here](https://api.wandb.ai/report/carperai/w64l5tbk).
* Unfortunately, it seems that the automated report does not render the parallel coordinates plot properly, see [here](https://api.wandb.ai/report/carperai/dag2pod4). Is this intended behavior and how it was produced previously? Thanks!

**Comment by ayulockin** [comment]
Hey @jon-tow the parallel coordinate plot is rendering properly for me. 

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/31141479/210505245-ab21839a-7db5-4632-b0b1-4073f65ae5c5.png">


Am I missing something?

**Comment by jon-tow** [comment]
Sorry, I accidentally deleted the automated report from: https://github.com/CarperAI/trlx/blob/17df88e618595c8c51ad95a5635156128abd6608/trlx/ray_tune/wandb.py#L84
See the updated link [here](https://wandb.ai/carperai/sweep/reports/Hyperparameter-Optimization-Report-main_2023-01-04_08-22-25--VmlldzozMjYxODcx), and more specifically, the following plot:
<img width="717" alt="Screenshot 2023-01-04 at 03 36 50" src="https://user-images.githubusercontent.com/41410219/210515467-b8206847-3783-434a-b3dd-7620bd4c5546.png">

**Comment by LouisCastricato** [comment]
Oh that's kinda weird

**Comment by ayulockin** [comment]
@jon-tow when I try to edit the report manually I can totally see the values being logged and thus I was able to manually fix it. Not sure why it's not rendering properly in the first place. Sharing with the team internally. I will let you all know when I learn something.

Can you let me know which browser and which wandb version were you using?

**Comment by jon-tow** [comment]
`wandb==0.13.7` 
`Chrome Version 108.0.5359.124 (arm64)`

Thank you!

**Comment by LouisCastricato** [comment]
This is now resolved.
