### ISSUE TITLE
Text generation 

### ISSUE THREAD

**Issue by imrankh46** [CarperAI/trlx#168]
### 📚 The doc issue

I have poetry dataset, which contains on prompt and completion colum. 
My question is should I need to train hugging face gpt2 or other model first and then those model pass into the trlx API ?

Can some one suggest a good example!

### Suggest a potential alternative/fix

😑

**Comment by LouisCastricato** [comment]
you should fine tune on the poetry first. Do you have any reward data or a way to construct a reward signal? This [example](https://github.com/CarperAI/trlx/blob/main/examples/architext.py) might be most relevant to you.

**Comment by imrankh46** [comment]
> 

2nd question is, how I can make reward data ?

**Comment by LouisCastricato** [comment]
No your dataset is insufficient to apply reinforcement learning. Unless you have some signal about which completions are preferred, or some way to approximate which are preferred (eg poems that rhyme are better than poems that don't) then you cannot apply RL. I would recommend you just finetune the language model on prompt+completions if you haven't already. I'm closing this issue.

**Comment by imrankh46** [comment]
> No your dataset is insufficient to apply reinforcement learning. Unless you have some signal about which completions are preferred, or some way to approximate which are preferred (eg poems that rhyme are better than poems that don't) then you cannot apply RL. I would recommend you just finetune the language model on prompt+completions if you haven't already. I'm closing this issue.

Thanks

**Comment by pranayj77** [comment]
I have a question on this. In your readme, you should an example of training using trlx with a prompt completion dataset. Isn't this similar to what was being asked? I am also trying to do something similar

**Comment by pranayj77** [comment]
@LouisCastricato
