### ISSUE TITLE
Best practice for loading `AutoModel` from `GPTHydraHeadWithValueModel` checkpoints?

### ISSUE THREAD

**Issue by paulbricman** [CarperAI/trlx#169]
Hi,

I trained a model using `trlx`, and I have checkpoints stored locally.

1. Simply loading the model from the checkpoints using `AutoModel.from_pretrained(path)` errored out due to there being no `config.json` file saved together with the `.bin` file. Anyway, this one I sorted out by copy-pasting the config.json of the original pretrained model I fine-tuned, which I found on HF Hub. **Just to confirm, does this seem appropriate?**

2. However, when loading the model using the above call, I get the warnings below. I've run into similar warnings before (when loading a pretrained HF model for a slightly different task), but not with so many weights listed as problematic. I assume this is caused by `trlx` initializing a `GPTHydraHeadWithValueModel` instance from the initial weights, which might not play nice with the vanilla-HF `AutoModel`? **What are best practices for getting from trlx fine-tuning checkpoints to model on HF hub to be loaded with `transformers`?**

Cheers,
Paul

```
m=AutoModel.from_pretrained("./ckpts")
Some weights of the model checkpoint at ./ckpts were not used when initializing GPT2Model: ['gpt.transformer.h.4.mlp.c_fc.bias', 'gpt.transformer.h.3.ln_1.weight', 'frozen_head.h.1.attn.c_attn.weight', 'gpt.transformer.h.0.ln_2.bias', 'frozen_head.h.0.ln_1.weight', 'gpt.transformer.h.2.attn.bias', 'gpt.transformer.h.5.attn.c_proj.bias', 'gpt.transformer.h.2.ln_1.weight', 'gpt.transformer.h.5.attn.c_attn.weight', 'gpt.transformer.h.5.mlp.c_fc.weight', 'frozen_head.h.1.ln_1.bias', 'gpt.transformer.h.5.attn.c_attn.bias', 'frozen_head.h.1.mlp.c_fc.bias', 'gpt.transformer.h.2.ln_2.weight', 'gpt.transformer.wpe.weight', 'v_head.0.bias', 'gpt.transformer.h.3.attn.c_proj.weight', 'gpt.transformer.h.4.ln_2.bias', 'frozen_head.h.0.mlp.c_fc.weight', 'v_head.2.weight', 'gpt.transformer.h.0.attn.c_attn.weight', 'gpt.transformer.h.3.mlp.c_fc.bias', 'gpt.transformer.h.2.mlp.c_proj.bias', 'frozen_head.h.0.ln_2.bias', 'gpt.transformer.h.1.ln_1.bias', 'frozen_head.h.1.attn.masked_bias', 'gpt.transformer.h.3.ln_2.weight', 'gpt.transformer.h.0.mlp.c_fc.weight', 'gpt.transformer.h.3.attn.c_proj.bias', 'gpt.transformer.h.2.ln_2.bias', 'gpt.transformer.h.5.mlp.c_fc.bias', 'gpt.transformer.h.4.attn.bias', 'frozen_head.h.0.mlp.c_proj.bias', 'frozen_head.h.1.ln_2.bias', 'frozen_head.h.0.attn.c_proj.bias', 'gpt.transformer.h.1.attn.c_attn.bias', 'gpt.transformer.h.4.attn.c_attn.weight', 'gpt.transformer.h.5.attn.bias', 'frozen_head.h.1.attn.c_attn.bias', 'gpt.transformer.h.2.attn.c_proj.weight', 'gpt.transformer.h.3.attn.c_attn.bias', 'frozen_head.h.0.mlp.c_fc.bias', 'frozen_head.lm_head.weight', 'gpt.transformer.h.5.ln_1.weight', 'gpt.transformer.h.3.attn.c_attn.weight', 'gpt.transformer.h.1.attn.c_attn.weight', 'gpt.transformer.h.1.mlp.c_proj.weight', 'gpt.transformer.h.1.attn.masked_bias', 'gpt.transformer.h.5.attn.c_proj.weight', 'frozen_head.h.1.ln_2.weight', 'gpt.lm_head.weight', 'gpt.transformer.h.2.attn.c_attn.weight', 'gpt.transformer.ln_f.weight', 'frozen_head.h.0.ln_1.bias', 'gpt.transformer.h.0.mlp.c_proj.weight', 'gpt.transformer.h.2.ln_1.bias', 'frozen_head.ln_f.weight', 'gpt.transformer.h.5.ln_2.weight', 'gpt.transformer.h.4.ln_2.weight', 'gpt.transformer.h.4.attn.c_proj.bias', 'gpt.transformer.h.3.attn.masked_bias', 'frozen_head.h.0.attn.c_attn.weight', 'gpt.transformer.h.2.attn.c_proj.bias', 'gpt.transformer.h.1.ln_2.bias', 'gpt.transformer.h.4.ln_1.bias', 'v_head.2.bias', 'frozen_head.h.0.attn.c_attn.bias', 'gpt.transformer.h.1.ln_2.weight', 'gpt.transformer.h.5.attn.masked_bias', 'gpt.transformer.h.3.attn.bias', 'frozen_head.h.0.attn.masked_bias', 'gpt.transformer.h.2.mlp.c_proj.weight', 'gpt.transformer.h.0.attn.masked_bias', 'gpt.transformer.h.4.mlp.c_proj.weight', 'gpt.transformer.h.2.mlp.c_fc.weight', 'frozen_head.h.0.ln_2.weight', 'gpt.transformer.h.5.ln_1.bias', 'gpt.transformer.h.5.mlp.c_proj.weight', 'gpt.transformer.h.0.ln_2.weight', 'gpt.transformer.h.5.ln_2.bias', 'gpt.transformer.h.2.attn.masked_bias', 'gpt.transformer.h.2.attn.c_attn.bias', 'gpt.transformer.h.1.attn.bias', 'gpt.transformer.h.0.mlp.c_fc.bias', 'gpt.transformer.h.4.mlp.c_fc.weight', 'gpt.transformer.h.1.mlp.c_fc.weight', 'gpt.transformer.h.0.attn.c_proj.bias', 'gpt.transformer.h.4.attn.masked_bias', 'frozen_head.h.1.attn.c_proj.weight', 'gpt.transformer.h.4.attn.c_proj.weight', 'frozen_head.h.1.ln_1.weight', 'frozen_head.ln_f.bias', 'gpt.transformer.h.4.ln_1.weight', 'gpt.transformer.h.1.mlp.c_fc.bias', 'frozen_head.h.1.attn.bias', 'gpt.transformer.wte.weight', 'gpt.transformer.h.3.mlp.c_fc.weight', 'frozen_head.h.0.attn.bias', 'gpt.transformer.h.3.ln_2.bias', 'gpt.transformer.ln_f.bias', 'gpt.transformer.h.0.mlp.c_proj.bias', 'frozen_head.h.0.attn.c_proj.weight', 'gpt.transformer.h.0.attn.c_attn.bias', 'gpt.transformer.h.3.mlp.c_proj.bias', 'gpt.transformer.h.1.attn.c_proj.weight', 'gpt.transformer.h.4.mlp.c_proj.bias', 'gpt.transformer.h.0.ln_1.weight', 'gpt.transformer.h.0.attn.bias', 'gpt.transformer.h.1.mlp.c_proj.bias', 'gpt.transformer.h.3.ln_1.bias', 'gpt.transformer.h.5.mlp.c_proj.bias', 'gpt.transformer.h.0.attn.c_proj.weight', 'frozen_head.h.1.mlp.c_proj.weight', 'gpt.transformer.h.0.ln_1.bias', 'gpt.transformer.h.1.ln_1.weight', 'gpt.transformer.h.2.mlp.c_fc.bias', 'frozen_head.h.0.mlp.c_proj.weight', 'frozen_head.h.1.mlp.c_proj.bias', 'v_head.0.weight', 'gpt.transformer.h.4.attn.c_attn.bias', 'frozen_head.h.1.attn.c_proj.bias', 'gpt.transformer.h.1.attn.c_proj.bias', 'gpt.transformer.h.3.mlp.c_proj.weight', 'frozen_head.h.1.mlp.c_fc.weight']
- This IS expected if you are initializing GPT2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing GPT2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of GPT2Model were not initialized from the model checkpoint at ./ckpts and are newly initialized: ['h.5.ln_2.weight', 'h.5.ln_2.bias', 'h.3.attn.c_proj.bias', 'h.3.mlp.c_fc.weight', 'h.1.ln_2.bias', 'h.5.mlp.c_proj.bias', 'h.0.ln_1.bias', 'h.3.attn.bias', 'h.5.attn.bias', 'h.3.ln_1.bias', 'h.1.mlp.c_proj.bias', 'ln_f.weight', 'h.4.mlp.c_fc.weight', 'h.1.mlp.c_proj.weight', 'h.1.attn.bias', 'h.5.mlp.c_fc.weight', 'h.4.ln_2.weight', 'h.4.ln_2.bias', 'h.1.mlp.c_fc.weight', 'h.3.ln_2.weight', 'h.2.ln_1.weight', 'h.2.mlp.c_proj.weight', 'h.5.attn.c_attn.weight', 'h.5.ln_1.weight', 'h.3.attn.c_attn.bias', 'h.0.mlp.c_fc.bias', 'h.0.mlp.c_fc.weight', 'h.2.attn.c_proj.weight', 'h.2.mlp.c_proj.bias', 'h.1.attn.c_attn.bias', 'h.1.ln_2.weight', 'h.5.ln_1.bias', 'h.4.attn.c_proj.bias', 'h.1.attn.c_proj.weight', 'h.2.attn.c_proj.bias', 'h.4.attn.c_proj.weight', 'h.3.mlp.c_proj.bias', 'h.2.ln_2.weight', 'h.3.ln_1.weight', 'h.1.ln_1.bias', 'h.1.ln_1.weight', 'h.1.attn.c_proj.bias', 'h.0.ln_2.bias', 'h.1.attn.c_attn.weight', 'h.3.attn.c_attn.weight', 'h.4.attn.c_attn.bias', 'h.2.mlp.c_fc.weight', 'h.0.attn.c_attn.weight', 'h.2.ln_2.bias', 'h.4.mlp.c_proj.bias', 'h.2.mlp.c_fc.bias', 'h.0.attn.bias', 'h.4.attn.bias', 'h.0.attn.c_proj.bias', 'h.4.ln_1.weight', 'h.5.mlp.c_fc.bias', 'h.3.attn.c_proj.weight', 'h.2.attn.bias', 'h.4.attn.c_attn.weight', 'wte.weight', 'h.2.ln_1.bias', 'h.1.mlp.c_fc.bias', 'h.0.mlp.c_proj.bias', 'h.0.ln_1.weight', 'ln_f.bias', 'h.4.mlp.c_proj.weight', 'h.0.attn.c_attn.bias', 'wpe.weight', 'h.3.ln_2.bias', 'h.3.mlp.c_proj.weight', 'h.0.ln_2.weight', 'h.0.mlp.c_proj.weight', 'h.3.mlp.c_fc.bias', 'h.4.mlp.c_fc.bias', 'h.5.attn.c_proj.weight', 'h.4.ln_1.bias', 'h.0.attn.c_proj.weight', 'h.5.mlp.c_proj.weight', 'h.5.attn.c_attn.bias', 'h.2.attn.c_attn.weight', 'h.2.attn.c_attn.bias', 'h.5.attn.c_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

**Comment by PhungVanDuy** [comment]
Assume that you have a checkpoint folder after trlx training is `ckpts` and your based model is GPT-J. You can do these steps:
1. Use the load function from trainer to load trlx's checkpoint folder.
```python
trainer = get_trainer(config.train.trainer)(config)
trainer.load('ckpts')
```

2. Save the base model checkpoint to bin file (e.g. trlx_gptj.bin).

```python 
troch.save(trainer.model.base_model.state_dict(), 'trlx_gptj.bin')
```
4. Load this bin file to the GPT-J model and use it like transformers models.
```python
model = transformers.AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-j-6B")
model.load_state_dict(torch.load('trlx_gptj.bin'))
```

**Comment by LouisCastricato** [comment]
@paulbricman we are going to add this to the readme. Thanks.

**Comment by paulbricman** [comment]
Thanks @PhungVanDuy for the guidelines. I tried following them, but got the following error:

![image](https://user-images.githubusercontent.com/20104026/212682619-aff9fe9c-59e3-45c7-ae92-8c56a6d0c790.png)

And on it goes for more weights.

I should note that I used DeepSpeed for training, and so used the `zero_to_fp32.py` script to generate the `pytorch_model.bin`.

**Comment by paulbricman** [comment]
Ok, so what seems to work is to `trainer.save_pretrained` at the end of the training loop. The resulting `hf_model` folder seems to work fine with `GPTJForCausalLM.from_pretrained` (in my case). Even better, there are no complaints about params not being loaded!

However, I still couldn't get the output of `trainer.save` to load with `transformers`, at least in my specific setup (i.e. DeepSpeed, GPT-J...). I think this has several implications:
- If the user does not explicitly `trainer.save_pretrained` at the end of training, then they might not be able to get their model working with `transformers` that easily. I can't tell if some crucial info is being lost, or if it's just in the wrong format. Either way, it's more cumbersome. Maintainers might need to bake the `save_pretrained` call in the training loop so that one doesn't end up not being able to use the outcome of a long training run.
- The README at the moment appears to be partially wrong in guiding users in exporting to the HF hub. It suggests `trainer.save` instead of `trainer.save_pretrained` which might work in some cases, but it happened not to work with my setup.

**Comment by jon-tow** [comment]
Thanks for the detailed update @paulbricman ! 

> If the user does not explicitly `trainer.save_pretrained` at the end of training, then they might not be able to get their model working with transformers that easily. I can't tell if some crucial info is being lost, or if it's just in the wrong format. Either way, it's more cumbersome. Maintainers might need to bake the `save_pretrained` call in the training loop so that one doesn't end up not being able to use the outcome of a long training run.
* I agree; this is way less than ideal. At the moment if a user does not explicitly call `trainer.save_pretrained` they can convert the underlying model into an HF model for inference by first re-loading checkpoint states and running `trainer.save_pretrained` as done [here](https://gist.github.com/jon-tow/a6e1da299a075fc2db3b8ff637ab0dd0). Maybe this should be the default behavior on save?

> The README at the moment appears to be partially wrong in guiding users in exporting to the HF hub. It suggests `trainer.save` instead of `trainer.save_pretrained` which might work in some cases, but it happened not to work with my setup.

* Yes, the guide is wrong on how to prep models for the HF Hub; I'll update it. Thanks for pointing it out 🙏 

The naming was indeed to follow `transformers` but I'd be open to renaming it to `save_finetuned` or something of the sort. (CC @LouisCastricato for thoughts on this confusion).
