### ISSUE TITLE
Implement model saving/loading

### ISSUE THREAD

**Issue by Dahoas** [CarperAI/trlx#17]

**Comment by LouisCastricato** [comment]
We basically already have this no? Why can't we just allow the user to save the pytorch model directly

**Comment by Dahoas** [comment]
I think we should at least implement a quick convenience function so they can save the CausalModel without the value heads

**Comment by odellus** [comment]
It seems like any sort of [save strategy](https://huggingface.co/docs/transformers/v4.22.2/en/main_classes/trainer#transformers.TrainingArguments.save_strategy) either based on epoch or save_steps should probably be in the `configs/{implementation}_config.yml` file as well as in `trlx/data/configs.py`, which sort of makes it implementation independent imo. I mean yeah the user is expected to write their own self.learn() and they'd choose how to go about saving based on steps or epochs, but having that in TrainConfig dataclass ready to be used would be nice.

**Comment by LouisCastricato** [comment]
@odellus Do you want to go about implementing this?

**Comment by LouisCastricato** [comment]
Happy to assign you :)

**Comment by odellus** [comment]
Wanted to keep it minimal for first iteration. Just a single save_steps parameter. Will look into duplicating full HF trainer strategy options w/examples if there is interest.
