### ISSUE TITLE
Add optional dependency container file

### ISSUE THREAD

**Issue by jon-tow** [CarperAI/trlx#170]
### 🚀 The feature, motivation, and pitch

We should consider adding a file that contains dependency availability checks and imports following [this](https://github.com/CarperAI/trlx/pull/110#discussion_r1064177499) suggestion. Currently, we collect module import checks through multiple files:
https://github.com/CarperAI/trlx/blob/e9c6c863efe056989b43a5ef9960c7b864917227/trlx/utils/modeling.py#L11-L22

and

https://github.com/CarperAI/trlx/blob/e9c6c863efe056989b43a5ef9960c7b864917227/trlx/utils/__init__.py#L78-L86

This could be helpful in the future as useful but optional packages come to our attention.

**Comment by alan-cooney** [comment]
Doesn't Python throw an import error automatically?

**Comment by reciprocated** [comment]
Those are optional dependecies, so unless one asks for a specific feature in the training config they won't see the import error associated with it
