### ISSUE TITLE
Add tokenizer truncation side option

### ISSUE THREAD

**Issue by jon-tow** [CarperAI/trlx#177]
### 🚀 The feature, motivation, and pitch

Some tasks may benefit from truncating on different sides of batched prompts. We should add a configuration option to handle this from a high level as discussed [here](https://github.com/CarperAI/trlx/pull/145). Pasting discussion for quick view:

<img width="737" alt="Screenshot 2023-01-09 at 16 28 43" src="https://user-images.githubusercontent.com/41410219/211411825-7b107841-ecff-4603-8ef1-6d6bbb851b4b.png">

CC @reciprocated and @PhungVanDuy just in case y'all would like to add any extra comments or context.

**Comment by PhungVanDuy** [comment]
Thank you for this issue, should we also consider adding the padding side along with the truncation side?
