### ISSUE TITLE
Add CI/CD to build docs in order to avoid codebase-docs inconsistency?

### ISSUE THREAD

**Issue by paulbricman** [CarperAI/trlx#182]
I've never set up docs on `readthedocs`, but I imagine there can be some GitHub Action set up to build them from the source code on each commit on master?

For instance, the docs mention `trlx.model` stuffs, but it has all been renamed to `trlx.trainer` stuffs if you dive into the commit histories.

**Comment by reciprocated** [comment]
Hey Paul, thanks for bringing this up! trlX's documentation does lag a tiny bit and there was just recently an issue created to explore options to remedy that. To not split the discussion I'm going to have to close this one in favor of the former, but please feel free to reopen if you had something different in mind!
- https://github.com/CarperAI/trlx/issues/176
