### ISSUE TITLE
Script freeze with DeepSpeed

### ISSUE THREAD

**Issue by OleksandrKorovii** [CarperAI/trlx#187]
### 🐛 Describe the bug

I try to run example `accelerate launch examples/ppo_sentiments.py` and after 100 steps script freeze last line in logs: 

`[2023-01-13 15:55:38,937] [INFO] [logging.py:68:log_dist] [Rank 0] [Torch] Checkpoint pytorch_model is begin to save!`

I was waiting during 1 hour, but nothing happened. I saw 100% load on my gpus in `nvidia-smi`.
I used DeepSpeed. I've tried  stage 1 and 2 - same result.

**BUT without  _DeepSpeed_ everything works fine**

### Which trlX version are you using?
install from source

### Additional system and package information

Python version: 3.10
GPU: 2x RTX3090Ti
accelerate==0.15.0
bitsandbytes==0.36.0.post2
deepspeed==0.7.7
tokenizers==0.13.2
torch==1.12.1+cu116
transformers==4.25.1

**Comment by LouisCastricato** [comment]
This issue was resolved yesterday. Please pull from main. Thanks.
