### ISSUE TITLE
Initialization of value network

### ISSUE THREAD

**Issue by xiaoda99** [CarperAI/trlx#203]
In [Implementing RLHF: Learning to Summarize with trlX](https://wandb.ai/carperai/summarize_RLHF/reports/Implementing-RLHF-Learning-to-Summarize-with-trlX--VmlldzozMzAwODM2) it is mentioned:
“The PPO algorithm uses a value function which can be a deep learning model. In our case, this Value function is the GPT-J model initialized with the weights of the trained reward model. The Value function is not initialized with SFT model to prevents updates to the value function from partially destroying the pretrained policy (SFT mdoel) early in training.”

It is also mentioned in the original "Learning to summarize from human feedback" paper:
"For PPO, we run with separate policy and value networks, initializing our policies to the supervised baseline, and our value functions to the reward model."

However, I could not find the code of initializing value network with the weights of the reward model.  Could you explain (better show me the piece of code) how the value network is initialized in trlx?
- Da Xiao

**Comment by LouisCastricato** [comment]
Technically learning to summarize did something slightly different where they use an entirely separate model from the policy model to compute the value. Our value head is just stacked on top of the student model. Look towards the Hydra implementation, it might help you. https://github.com/CarperAI/trlx/blob/84a07113d8ced1497c5a7941a02f9c534bb4e185/trlx/trainer/nn/ppo_models.py#L300
