### ISSUE TITLE
Bug when trying to log with other trackers that not wandb

### ISSUE THREAD

**Issue by microsoft-fevieira** [CarperAI/trlx#207]
### 🐛 Describe the bug

When setting up the trackers to anything that is not "wandb", e.g. "all" or "tensorboard", it is causing trouble in BaseRLTrainer constructor, because logging_dir is being set to None and there is a failure building the path for logging.

### Which trlX version are you using?

latest

**Comment by LouisCastricato** [comment]
Thanks, at the moment TRLX is deeply integrated with weights and biases. The tracker class is there incase in the future we support other trackers. If you want to create a PR that rectifies tensorboard support I would be happy to merge it. Would be an easy way to become a contributor :)

**Comment by marcobellagente93** [comment]
Hi, I got the same problem while trying to develop on OpenELM without wandb, I can open a PR

**Comment by jon-tow** [comment]
> Hi, I got the same problem while trying to develop on OpenELM without wandb, I have a somewhat working solution, could open a PR

@marcobellagente93 Feel free to open a PR! I don't think anyone has begun one, so it'd be helpful 🙏

**Comment by marcobellagente93** [comment]
Here it is, if you want to have a look, pretty small: https://github.com/CarperAI/trlx/pull/209

**Comment by cat-state** [comment]
Closed by https://github.com/CarperAI/trlx/pull/209
