### ISSUE TITLE
trlx.train doesn't work in Google colab

### ISSUE THREAD

**Issue by sr5434** [CarperAI/trlx#211]
### 🐛 Describe the bug

In Google colab, I am trying to finetune GPT-2 on a reward-labeled dataset. Below is my code:
```
import trlx
trainer = trlx.train('gpt2', dataset=[('dolphins', 'geese'), (1.0, 100.0)])
```
I am sure that trlx is installed because it imports without issue. The error message states:
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-25-5fc72a832a7b>](https://localhost:8080/#) in <module>
----> 1 trainer = t.train('gpt2', dataset=[('dolphins', 'geese'), (1.0, 100.0)])

AttributeError: module 'trlx' has no attribute 'train'
```
How can I fix this issue?

### Which trlX version are you using?

trlx===0.3.0

### Additional system and package information

Google Colab default runtime

**Comment by LouisCastricato** [comment]
You installed TRLX incorrectly. Please restart colab after installation, otherwise it won't recognize the new package.

**Comment by LouisCastricato** [comment]
Closing since this is not an issue with TRLX.

**Comment by jon-tow** [comment]
TRLX training doesn't work in colab at the moment because `git` tagging is required for experiment tracking and colab does not come pre-installed with `git`.

Repro: https://colab.research.google.com/drive/16rREmUPLYx2c43IikDSg4yrRDLa3ScQS?usp=sharing

We can make the `git` tracking optional to fix this - reopening for awareness.

**Comment by jon-tow** [comment]
Running from a clone in colab works as expected; see the examples: https://github.com/CarperAI/trlx#examples

For future reference, a __pip-installed__ version will __not__ work because of the git tagging I mentioned. This will need to be addressed in the future.

Closing for now.
