### ISSUE TITLE
GPT-j model training

### ISSUE THREAD

**Issue by l1f14bscs0388** [CarperAI/trlx#212]
Hi, kindly tell me which instance you use for GPT-J training or kindly tell me how many resources are required for GPT-J training

**Comment by jon-tow** [comment]
@l1f14bscs0388 without any details on the dataset/task you're fine-tuning for, it's hard to say what resources (cloud instances / locally) you'll need. We've been using Amazon EC2 P4 Instances for our use cases. This is probably better suited for discussion in our Discord server https://discord.gg/canadagoose
if you'd like to join 👍
