### ISSUE TITLE
Number of GPUs and training time needed to replicate OpenAI summarization rlhf experiments?

### ISSUE THREAD

**Issue by wenyong-h** [CarperAI/trlx#236]
I'm trying to replicate the experiments described in https://wandb.ai/carperai/summarize_RLHF/reports/Implementing-RLHF-Learning-to-Summarize-with-trlX--VmlldzozMzAwODM2.
But I didn't find infomation about number of GPUs and training time required for each of the SFT, Reward Modle, PPO stages.
Can you provide this information to help me and other users to better replicate your experiments?

**Comment by PhungVanDuy** [comment]
Thank you for your question, this is the setup that I have used for OpenAI summarization RLHF experiments
- SFT, Reward model: 8 GPUs A100 40GB
- PPO: 2 GPUs A100 40GB (one for reward model inference, one for PPO learning)
