### ISSUE TITLE
Verbosity during Rollout + Eval stages in trlx training

### ISSUE THREAD

**Issue by JustinAWei** [CarperAI/trlx#239]
### 🚀 The feature, motivation, and pitch

I may be missing something, but the eval and rollout stages are a black box to me. The only insight I get into what is happening during these phases is prints in `reward_fn`. This is especially problematic with larger sequence_len and num_rollouts.

I recently came across a particularly hard-to-debug issue where having anything but a trivial size for the eval set (during multi-gpu training) would cause GPUs to time out its `NCC AllGather` operation due to the reward model taking 30+ minutes on the eval set. 

I had no idea what was going on under the hood at all and eventually figured out the problem via ablations of config values and checking GPU power usage graphs. If there was some indication on the stage of the training (eval) or the operation (waiting on reward model for eval rewards), this would've been way easier. 

As of now, after understanding some of the code, my strategy for debugging has been to add prints in the source code and rebuild the library; however, it would be such a QoL thing to have information on the main phases of training for other who might want to debug things in this library without needing to read a lot of the source code.

**Comment by JustinAWei** [comment]
I have thought about contributing the prints myself but I am not confident I understand the full library yet

**Comment by jon-tow** [comment]
Agreed - we'll be looking into this ASAP

Related Issues:
- [ ] #178

**Comment by jon-tow** [comment]
Initial verbosity support has been merged. See usage details [here](https://github.com/CarperAI/trlx#logging). Please let us know if there is any other information you'd like to see logged during training.

Thank you for raising this issue!
