### ISSUE TITLE
Incorrect paper link in summarize_rlhf example README.MD

### ISSUE THREAD

**Issue by jboboyle** [CarperAI/trlx#240]
### 📚 The doc issue

The example [summarize_rlhf readme](https://github.com/CarperAI/trlx/tree/main/examples/summarize_rlhf) has an incorrect link to the Stiennon et al.'s Learning to Summarize from Human Feedback. It currently links to: https://arxiv.org/abs/2106.00987

### Suggest a potential alternative/fix

Link to: https://arxiv.org/abs/2009.01325

**Comment by jon-tow** [comment]
Updated. Thank you!
