### ISSUE TITLE
eval duplication for multi gpu

### ISSUE THREAD

**Issue by JustinAWei** [CarperAI/trlx#247]
### 🐛 Describe the bug

For PPO training, there are `NUM_GPU * EVAL_SIZE` entries under Tables `runs.summary["samples"]` in WandB. Each GPU seems to be running the eval set completely instead of sharing the work. Note that I am using deepspeed with O2 but I am not sure if it is only a deepspeed thing. 

### Which trlX version are you using?

0.3.0

**Comment by reciprocated** [comment]
You're right and also this is oddly ppo/deepspeed specific, for ppo/ddp there would be sharing of work however also still with some duplication in case when `len(eval_prompts)` is not divisible by `NUM_GPU * batch_size`. I agree that this is not expected if you are concernced not only about the expected reward on mostly uniform prompts
