### ISSUE TITLE
how to load from a ckpt to continue training?

### ISSUE THREAD

**Issue by JustinAWei** [CarperAI/trlx#252]
### 📚 The doc issue

I see there is a `load()` fn on `accelerate_base_trainer.py` but I don't see it being used anywhere. It seems like perhaps I need to create my own PPOTrainer and call `load()`, then pass it into trlx? or do something like `trlx.get_trainer().load()`?

```
   def load(self, directory=None):
        """Load checkpoint of optimizer, scheduler and a model"""
        self.accelerator.load_state(directory or self.config.train.checkpoint_dir)
```

**Comment by LouisCastricato** [comment]
Someone wrote a script with built in checkpoint recovery, I forgot who. This is something we need natively though. @reciprocated @PhungVanDuy @jon-tow

**Comment by scarydemon2** [comment]
Is there any progress? I ran into the same problem, I need to initialize the ppo model with the sft checkpoint

**Comment by ps602** [comment]
I have the same issue too, is there any other closed issue or documentation we can refer to?
