### ISSUE TITLE
Unexpected tokenization behavior of `PromptPipeline`

### ISSUE THREAD

**Issue by ZHAOTING** [CarperAI/trlx#253]
### 🐛 Describe the bug

I am not sure whether this is intended or not, but in the `init()` of a `PromptPipeline`, prompt texts are converted to input id and attention mask tensors with a default value of `add_special_tokens=True` at [L20](https://github.com/CarperAI/trlx/blob/main/trlx/pipeline/offline_pipeline.py#L20).

For some tokenizers, it adds BOS and EOS tokens to the prompt, which might not be expected.
In my case, my policy model will generate nothing but another EOS token after seeing an EOS. This results in empty rewards and leads to [an endless loop when an orchestrator attempts to add new PPOElements].(https://github.com/CarperAI/trlx/blob/add-hh-example/trlx/orchestrator/ppo_orchestrator.py#L222).

### Which trlX version are you using?

Branch add-hh-example. At the [latest commit](https://github.com/CarperAI/trlx/commit/9745ec360ee43cafd3b63f213dbf04ca212e5e35).

**Comment by LouisCastricato** [comment]
@jon-tow easy fix

**Comment by cat-state** [comment]
Thanks for this issue, I just ran into this issue yesterday too.

**Comment by cat-state** [comment]
@ZHAOTING it should be solved after merging #287 , let me know if it fixed it for your model

**Comment by ZHAOTING** [comment]
@cat-state my experiment looks good at commit [b91da7b](b91da7b03d8e9fa0c0d6dce10a8f2611aca3013f).
Thanks for the fix!
