### ISSUE TITLE
devcontainer fails because pylance can't be installed

### ISSUE THREAD

**Issue by derpyplops** [CarperAI/trlx#295]
### 🐛 Describe the bug

When I tried building the devcontainer with vscode on my m2 mac, I was only able to install it after uncommenting pylance from the pip installs. Then when I try to install it I get 

```
$ pip install pylance
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pylance (from versions: 0.0.2)
ERROR: No matching distribution found for pylance
```

**Comment by jon-tow** [comment]
Hi @derpyplops ! The Pylance language server isn't pip installable so it should be removed from the Dockerfile. The [`Python` extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) should automatically install Pylance for you - can you check your installed VS Code extensions to see if it's there?

**Comment by jon-tow** [comment]
Thanks for reporting 🙏
