### ISSUE TITLE
Pass extra information for the reward function with every sample.

### ISSUE THREAD

**Issue by JulesGM** [CarperAI/trlx#301]
### 🚀 The feature, motivation, and pitch

There are multiple situations where having more information about the sample than just the string would be good with the reward function. A very dumb example is if you want spanish sentences to be shorter and english sentences to be longer. You would have to pass the language of the sample. 

The only option right now is to use a hashmap, however, this has disadvantages. 
 - It requires keeping the whole dataset in memory
 - Because of tokenization artifacts, the access may sometimes break
 - It breaks expectations of how this should work. People likely expect just to be able to pass information with the dataset object.

As library a builder it's hard to predict all the uses that the library will have, so I suggest just being able to pass a dict per sample with the dataloader, and to pass a list of dicts to the reward function.

**Comment by maxreciprocate** [comment]
Resolved with https://github.com/CarperAI/trlx/pull/421
