### ISSUE TITLE
Runtime Error:`FlatParameter` requires uniform `requires_grad`  

### ISSUE THREAD

**Issue by jihan-yin** [CarperAI/trlx#313]
### 🐛 Describe the bug

I'm trying to run the `examples/summarize_daily_cnn/t5_summarize_daily_cnn.py` script with the example accelerate config. I'm getting a run time error when I try to do so, with `'FlatParameter' requires uniform 'requires_grad'`. This occurs when we try to use accelerate to prepare the model in the trainer code.

I'm pretty sure this is because Accelerate tries wrapping the model with pytorch FSDP, which doesn't support layer freezing. But, I know in this repo we freeze the bottom layers of our model. So that's probably where the error is coming from.

It's weird that no one else seems to be running into this error. Can someone help me see what's going on here?

### Which trlX version are you using?

latest dev version

### Additional system and package information

python==3.8.16, pytorch=='1.13.1+cu116', accelerate==0.16.0

**Comment by jihan-yin** [comment]
Did a bit more debugging and realized my accelerate launcher wasn't using `DEEPSPEED` as the distributed type, even though it is set in the config file and I'm passing it as an arg. Doesn't look like the issue is with trlx, so closing

**Comment by REIGN12** [comment]
Hi, I am using another repo which only tune parts of the LLM and ran into the same issue; So if the deepspeed is used, the problems will be solved? I am like a totally newbie in this area, if the deepspeed can solve this, why? Many thanks for any responses!
