### ISSUE TITLE
Accelerate supports Megatron-LM now. Why use NeMo rather than directly Accelerate with Megatron-LM as the backend?

### ISSUE THREAD

**Issue by jack-Dong** [CarperAI/trlx#330]
https://huggingface.co/docs/accelerate/usage_guides/megatron_lm

**Comment by Dahoas** [comment]
We explored this option several months ago and ended up not going with it due to the rigidity integration.

**Comment by jack-Dong** [comment]
So, you mean the “Accelerate with Megatron-LM” is not suited for implementing RLHF architecture‘s training pipeline because of its rigidity integration？

**Comment by jack-Dong** [comment]
could you explain more detailly？

**Comment by reciprocated** [comment]
cc @cat-state

**Comment by cat-state** [comment]
> could you explain more detailly？

We did look at this before, and at the time (and it seems, currently too), the implementation only supports loading a fixed number of manually converted architectures into megatron-lm. As we have to implement custom architectures for RL, we would have needed to directly use megatron-lm to reimplement our achitectures anyway. See the https://github.com/CarperAI/trlx/blob/main/trlx/models/modeling_nemo_ilql.py for example.

**Comment by jack-Dong** [comment]
> > could you explain more detailly？
> 
> We did look at this before, and at the time (and it seems, currently too), the implementation only supports loading a fixed number of manually converted architectures into megatron-lm. As we have to implement custom architectures for RL, we would have needed to directly use megatron-lm to reimplement our achitectures anyway. See the https://github.com/CarperAI/trlx/blob/main/trlx/models/modeling_nemo_ilql.py for example.

OK， I got you， thanks for the time to explain。
