### ISSUE TITLE
Request NeMoPPOTrainer

### ISSUE THREAD

**Issue by jack-Dong** [CarperAI/trlx#335]
### 🚀 The feature, motivation, and pitch

The current PPOTrainer based on the Accelerate could not support larger model training ( e.g. >20B).
1) do you have a detailed roadmap to support NeMoPPOTrainer？
2) have you compared the performance between PPO and ILQL based on any task?

**Comment by LouisCastricato** [comment]
WIP. Closing issue as duplicate.
