### ISSUE TITLE
why compute total_steps like this?

### ISSUE THREAD

**Issue by akk-123** [CarperAI/trlx#339]
### 🐛 Describe the bug

In this [code](https://github.com/CarperAI/trlx/blob/main/trlx/trainer/accelerate_ppo_trainer.py#L238)
```python
self.total_steps = self.config.train.epochs * self.n_updates_per_batch * len(self.train_dataloader)
self.total_steps = min(self.total_steps, self.config.train.total_steps)
```
`len(self.train_dataloader)` always equa to 1, an epoch mean run all data once, so maybe there need to be `len(self.train_dataset)` rather than `len(self.train_dataloader)`？

**Comment by LouisCastricato** [comment]
@PhungVanDuy

**Comment by jon-tow** [comment]
Hi @akk-123! `len(self.train_dataloader)` should be equal to the number of batches collected from the `train_dataset`. If `batch_size >= num_examples` then this will always be 1. So the total steps as computed in the first line basically says: "for each mini-batch of data (`len(train_dataloader)`) take `n_updates_per_batch` steps and do this `epochs` number of times."

**Comment by akk-123** [comment]
@jon-tow but I run [ppo_sentiments.py](https://github.com/CarperAI/trlx/blob/e72f7d1a80/examples/ppo_sentiments.py), data is imdb, num_example is 50000, batch_size set 128, len(train_dataloader) also equal to 1

**Comment by reciprocated** [comment]
For PPO an epoch means one experience generation sampled off of prompts from the training dataset. This maps directly (if the mapping is too direct it can be replaced with a more expected option, or dropped altogether) to code in:
https://github.com/CarperAI/trlx/blob/e72f7d1a8008c9a994e9fe465aa4a8a7a1fb3232/trlx/trainer/accelerate_base_trainer.py#L468-L475
Then `len(self.train_dataloader)` is equal to the number of batches from `num_rollouts` of experience generations per epoch, so if `num_rollouts == batch_size == 128` it's going to be equal to `1`

**Comment by akk-123** [comment]
@reciprocated thanks for your reply，can you tell me after train a model, how to load ckpt and inference?

**Comment by reciprocated** [comment]
@akk-123 you can do
```python
trainer = trlx.train(...)
trainer.save_pretrained("model")
```

and use it as an ordinary hugging face model
```python
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("model")
model.generate(...)
```

[1] https://github.com/CarperAI/trlx#save-the-resulting-model-to-a-hugging-face-pretrained-language-model-ready-to-upload-to-the-hub

**Comment by akk-123** [comment]
OK，thanks
