### ISSUE TITLE
while i change num_processes = 2，the following error occurs, How to configure? thank you 

### ISSUE THREAD

**Issue by joytianya** [CarperAI/trlx#344]
### 🐛 Describe the bug

while i change num_processes = 2，the following error occurs, How to configure? thank you 
https://github.com/CarperAI/trlx/blob/main/examples/summarize_rlhf/configs/default_accelerate_config.yaml#L18
```python
RuntimeError: Expected all tensors to be on the same device, but found at least
two devices, cuda:0 and cuda:1! (when checking argument for argument index in
method wrapper__index_select)
```

### Which trlX version are you using?

pip install with github

### Additional system and package information

python3.8

**Comment by PhungVanDuy** [comment]
> 

Thank you for your information, this current implementation for summarization does not support training multi-GPUs. If you want to train on multi-GPUs you have to use triton to handle reward model inference. 

In terms of the error that you get above, I do not know what is the line in the code that raised this error. 
But if you wanna train the model on multi-GPUs you can check this example that I made [here](https://gist.github.com/PhungVanDuy/f29c00a77d5055e926ec8f5e702c8210#file-hashing_tomatch_ppo_summarize-py). 

Hope this answer can help you.

**Comment by joytianya** [comment]
ok, thank you ~
