### ISSUE TITLE
TLRX Wandb blogpost says value head should be initialized from reward model weights. This is not the case in the code.

### ISSUE THREAD

**Issue by jihan-yin** [CarperAI/trlx#345]
### 🐛 Describe the bug

In the `Gotcha 2` section of the [trlx wandb blogpost](https://wandb.ai/carperai/summarize_RLHF/reports/Implementing-RLHF-Learning-to-Summarize-with-trlX--VmlldzozMzAwODM2), there is a short passage that says:
>The PPO algorithm uses a value function which can be a deep learning model. In our case, this Value function is the GPT-J model initialized with the weights of the trained reward model. The Value function is not initialized with SFT model to prevents updates to the value function from partially destroying the pretrained policy (SFT mdoel) early in training.

This does not seem to be the case in the [codebase](https://github.com/CarperAI/trlx/blob/main/trlx/models/modeling_ppo.py#L264). We create a new value head on top of the policy model backbone, which is initialized from the SFT model. Nowhere in the codebase do we have separate weight loading for the value model. Is this a case of us having moved on from doing this since the blog post, due to better performance when the value model is not initialized from the reward model?

I'm also confused about why the blog post details that updates to the value function would partially destroy the SFT model. The value model would be completely separated from the policy model (except for the frozen layers) so why would it's updates affect the policy model at all?

Tagging @PhungVanDuy as you wrote the blog post.

**Comment by PhungVanDuy** [comment]
> 
Thank you for pointing that out. 

You are right, the Value function is initialized by SFT same as policy. @ayulockin you wrote this part can you edit it to fit with our hydra architecture?

**Comment by jihan-yin** [comment]
Okay, just to be clear, the blog post bit was incorrect and we should still be initializing the value model from the SFT model? Or should we try out initializing the value model from the reward model?

**Comment by PhungVanDuy** [comment]
> 

Yes, we still initializing from the SFT model.

**Comment by PhungVanDuy** [comment]
@jihan-yin you can check this paper [Sparrow](https://arxiv.org/pdf/2209.14375.pdf) figure 8 to get more insight from our implementation.

**Comment by PhungVanDuy** [comment]
Updated blog post, thank you for this finding.
