### ISSUE TITLE
examples/summarize_rlhf cannot run

### ISSUE THREAD

**Issue by magic282** [CarperAI/trlx#351]
### 🐛 Describe the bug

The example code cannot run.

1. `train_gptj_summarize.py`
This file needs the CarperAI/openai_summarize_tldr dataset. The dataset looks like:
```
>>> dataset
DatasetDict({
    train: Dataset({
        features: ['prompt', 'label'],
        num_rows: 116722
    })
    test: Dataset({
        features: ['prompt', 'label'],
        num_rows: 6553
    })
    validation: Dataset({
        features: ['prompt', 'label'],
        num_rows: 6447
    })
})

```
However, in the code https://github.com/CarperAI/trlx/blob/main/examples/summarize_rlhf/sft/train_gptj_summarize.py#L54 , it is `valid` here. In the downloaded dataset, it is called `validation`.

2. `rouge = evaluate.load("rouge")` seems to be wrong.
It raises an error:
```
FileNotFoundError: Couldn't find a module script at project/trlx/examples/summarize_rlhf/sft/rouge/rouge.py. Module 'rouge' doesn't exist on the Hugging Face Hub either.
```
with `rouge-score              0.1.2` installed.

### Which trlX version are you using?

0.5.0

**Comment by PhungVanDuy** [comment]
<img width="1030" alt="Screenshot 2023-03-03 at 16 55 52" src="https://user-images.githubusercontent.com/28798474/222676337-b5e3b0ef-d0d0-4fe2-97f4-5f8a22135685.png">
I just checked it is still fine. Can you check again?
Env: 
```bash
datasets==2.9.0
evaluate==0.4.0
```

**Comment by magic282** [comment]
I just found where the problem is.

Our cluster is not conntected to the internet. So the gptj model and the dataset are downloaded using `git clone`, which looks different from the one that huggingface downloads. Seems that it has some post processing step.

The rouge issue is similar. The `evaluate` package also needs internet to download `rouge.py`.
