### ISSUE TITLE
why freeze model when ppo training

### ISSUE THREAD

**Issue by akk-123** [CarperAI/trlx#355]
in config, num_layers_unfrozen = 2, why unfreeze last 2 layer rather than train full model?

**Comment by Hunter-P** [comment]
> in config, num_layers_unfrozen = 2, why unfreeze last 2 layer rather than train full model?

It freezes the last 2 layers rather than unfreeze the latest 2 layers, but  I have the same confusion: why freeze last 2 layer rather than train full model?

`
def freeze_bottom_causal_layers(model: nn.Module, num_layers_unfrozen: int = 0):
    """Freezes the bottom transformer block layers of the specified model."""
    hidden_layers = hf_get_causal_hidden_layers(model)
    if num_layers_unfrozen == 0:
        hidden_layers_to_freeze = list(hidden_layers)
    elif num_layers_unfrozen > 0:
        hidden_layers_to_freeze = list(hidden_layers)[:-num_layers_unfrozen]
    else:
        hidden_layers_to_freeze = []
    for layer in hidden_layers_to_freeze:
        layer.requires_grad_(False)
`

**Comment by LouisCastricato** [comment]
Tuning too much of the model with RLHF leads to the model producing incoherent text (gibberish). Also tuning just the last few layers is significantly faster with minimal to no performance degradation. It would be very hard to scale trlX to GPT3 sizes without this.
