### ISSUE TITLE
how to use trlx_inference_gptj.py to infer own trained model

### ISSUE THREAD

**Issue by Bo396543018** [CarperAI/trlx#365]
### 🚀 The feature, motivation, and pitch

Thank you for your great work.
I used scipts in summarize_rlhf train own ppo model(gpt-2) and tried to do inference.
After converting trained model to bin file and load from_pretrained, it seems that the model conversion is not fully aligned. Could you provide an example of converting a trained model for inference?

**Comment by PhungVanDuy** [comment]
Assume that you having checkpoint output is `best_checkpoint/pytorch_model/mp_rank_00_model_states.pt`. I guess you can try something like this:
```python
import torch
# Import the model architecture used during training and load the weights
from trlx.models.modeling_ppo import AutoModelForCausalLMWithHydraValueHead
model = AutoModelForCausalLMWithValueHead.from_pretrained("...")
model.load_state_dict(torch.load("best_checkpoint/pytorch_model/mp_rank_00_model_states.pt")["module"])
```

Another way that you can save your model directly to huggingface format by this refer this https://github.com/CarperAI/trlx#save-the-resulting-model-to-a-hugging-face-pretrained-language-model-ready-to-upload-to-the-hub.

**Comment by Bo396543018** [comment]
Thank you for replying.

**Comment by c-box** [comment]
> Assume that you having checkpoint output is `best_checkpoint/pytorch_model/mp_rank_00_model_states.pt`. I guess you can try something like this:
> 
> ```python
> import torch
> # Import the model architecture used during training and load the weights
> from trlx.models.modeling_ppo import AutoModelForCausalLMWithHydraValueHead
> model = AutoModelForCausalLMWithValueHead.from_pretrained("...")
> model.load_state_dict(torch.load("best_checkpoint/pytorch_model/mp_rank_00_model_states.pt")["module"])
> ```
> 
> Another way that you can save your model directly to huggingface format by this refer this https://github.com/CarperAI/trlx#save-the-resulting-model-to-a-hugging-face-pretrained-language-model-ready-to-upload-to-the-hub.

I have another question about this issue, when executing:
```python
trainer = trlx.train(config=config, reward_fn=lambda samples, **kwargs: [float(int(sample)) for sample in samples])
trainer.save_pretrained('/path/to/output/folder/')
```
Is the trainer storing the last checkpoint or the best checkpoint? 
I suspect that it is the last checkpoint? If so, how can I save the best checkpoint so that I can load it using:
```python
AutoModelForCausalLM.from_pretrained(path)
```

**Comment by sadahanu** [comment]
> Assume that you having checkpoint output is `best_checkpoint/pytorch_model/mp_rank_00_model_states.pt`. I guess you can try something like this:
> 
> ```python
> import torch
> # Import the model architecture used during training and load the weights
> from trlx.models.modeling_ppo import AutoModelForCausalLMWithHydraValueHead
> model = AutoModelForCausalLMWithValueHead.from_pretrained("...")
> model.load_state_dict(torch.load("best_checkpoint/pytorch_model/mp_rank_00_model_states.pt")["module"])
> ```
> 
> Another way that you can save your model directly to huggingface format by this refer this https://github.com/CarperAI/trlx#save-the-resulting-model-to-a-hugging-face-pretrained-language-model-ready-to-upload-to-the-hub.

This does not work for me. Getting errors as RuntimeError: Error(s) in loading state_dict for AutoModelForCausalLMWithHydraValueHead:
        Missing key(s) in state_dict:"base_model.transformer.wte.weight", "base_model.transformer.h.0.ln_1.weight", 
"base_model.transformer.h.0.ln_1.bias", "base_model.transformer.h.0.attn.bias", "base_model.transformer.h.0.attn.masked_bias", 
"base_model.transformer.h.0.attn.k_proj.weight", "base_model.transformer.h.0.attn.v_proj.weight", "base_model....
