### ISSUE TITLE
model parallel

### ISSUE THREAD

**Issue by beautifull4frank** [CarperAI/trlx#366]
Hello, I just successfully run "summarize_rlhf/trlx_gptj_text_summarization.py", but I am not sure whether it is implemented using model parallel or not. I have to run large size bloomz, so I need to seperate the huge mode into several gpus using model parallel.

**Comment by PhungVanDuy** [comment]
I got success running with 20B in parallel with this [script](https://gist.github.com/PhungVanDuy/52d7ffa99f8b5a171bbf078ea53b0d46). Please try.
