### ISSUE TITLE
Questions about model size and num_processes in summarize-rlhf

### ISSUE THREAD

**Issue by agave233** [CarperAI/trlx#367]
Hello,

I have a few questions about the summarize-rlhf PPO training:

(1) What is the maximum size of the model that can be loaded with summarize-rlhf? Is it possible to use model parallelism to accommodate larger models?

(2) What is the effect of increasing the num_processes parameter (e.g., setting it to 2 or 4)? Does it allow for larger models to be loaded or does it enable data parallelism for faster training? In my experiments, I found that increasing num_processes did not allow me to load larger models.

(3) I was able to train the gpt-neo-2.7B model using a V100 32G GPU, but when I tried to train the bloom-560m model with the same parameters, I encountered an out-of-memory (OOM) error. Could you please help me explain why this happened?

(4) I also want to confirm of you successfully train models with SFT and RM both set to 6B on two A100 40GB GPUs?

Thank you for your help!

**Comment by PhungVanDuy** [comment]
1. Tested on 20B and parallelism still working, but I guess you need to change the current script on the main repo, refer to this [one](https://gist.github.com/PhungVanDuy/52d7ffa99f8b5a171bbf078ea53b0d46). I will update this script to main repo in the next PR.
2. This could be resolved by the script above.
3. I guess it should be fine with V100 32GB for 2.7B, I haven't tested it, make sure that you use a small batch size, zero2 CPU offload, fp16.
4. Yes, it was able to run on A100 40GPUs for GPT-J.

**Comment by agave233** [comment]
Thanks a lot! Could you please provide the config files "default_accelerate_config.yaml" and "ds_config_trlx_gptj_summarize.json" if there is any change?

By the way, is the much larger 20B model successfully trained on a single GPU or eight GPUs? I found the device for the reward model is set to 7 in the code file.

**Comment by PhungVanDuy** [comment]
> Thanks a lot! Could you please provide the config files "default_accelerate_config.yaml" and "ds_config_trlx_gptj_summarize.json" if there is any change?
> 
> By the way, is the much larger 20B model successfully trained on a single GPU or eight GPUs? I found the device for the reward model is set to 7 in the code file.

`default_accelerate_config.yaml`: just change number process to 8 (depend on how many process that you want to run)
deepspeed config is same. 

Hope this will help you. Thanks.

**Comment by AlisonWen** [comment]
@PhungVanDuy 
I realized the [sample project of summarization](https://wandb.ai/carperai/summarize_RLHF/runs/lv9es38t/overview) was using the source code `trlx_gptneo_text_summarization.py`, but I cannot find the file anywhere??
I tried the current `trlx_gptj_text_summarization.py` and it cannot converge after 3500 steps
<img width="1349" alt="image" src="https://github.com/CarperAI/trlx/assets/77866896/3ba4fbfb-e2b0-49db-bd77-9104993d20ea">
