### ISSUE TITLE
Community Integration: Making CarperAI/trlx cheaper, faster, and more efficient

### ISSUE THREAD

**Issue by binmakeswell** [CarperAI/trlx#380]
### 🚀 The feature, motivation, and pitch

Thank you for your outstanding contribution to trlx!

AIGC, e.g., ChatGPT, has recently risen to be one of the hottest topics in AI. We are happy to share a fantastic solution where the costs of training/inference trlx can be cheaper a lot!

[Colossal-AI](https://github.com/hpcaitech/ColossalAI) provides an optimized open source low-cost solution that replicates ChatGPT training process. Compared to the PyTorch, a single-machine training process can be 7.73 times faster, and a mini demo training process requires only 1.62GB of GPU memory. More details can be found on the [blog](https://www.hpc-ai.tech/blog/colossal-ai-chatgpt).

Open-source code：https://github.com/hpcaitech/ColossalAI#chatgpt

We would appreciate it if we could build the integration with you to benefit the community, and we are willing to provide help you need in this cooperation for free, making efforts towards the era of large AI models from the starting point of replicating ChatGPT!

Thank you very much.

**Comment by cat-state** [comment]
Thank you for your kind words and interest in trlx!

However I don't think we would have the resources to integrate and maintain another integration at this time. It also seems Colossal-AI is mostly focused on using cpu-offload to lower the resource cost of tuning large models, which is a bit out of scope with our focus on tuning larger models using multi-node distributed training. 

If there's some way to use trlx as a library with Colossal-AI and other acceleration libs without requiring integration within trlx itself, that would be something we would potentially be interested in adding.

**Comment by binmakeswell** [comment]
Hi @cat-state Thank you for your quick response.

Actually, lowering the resource cost of tuning large models is just one of Colossal-AI features. It is also important for Colossal-AI to maximize the performance and efficiency of tuning larger models using multi-node distributed training. For example, We provide [the most parallel technologies](https://github.com/hpcaitech/ColossalAI#features) in the open source community and have validated them in models such as GPT-3 and ChatGPT.

For the usage, it's true that you can use Colossal-AI as a library, just as you use huggingface accelerate, NeMo-Megatron or Ray Tune. Here are examples of taking Colossal-AI as a library with [Stable Diffusion](https://github.com/hpcaitech/ColossalAI/tree/main/examples/images/diffusion) and [ChatGPT](https://github.com/hpcaitech/ColossalAI/tree/main/applications/ChatGPT).

Thank you very much.

**Comment by LouisCastricato** [comment]
Doesn't your RLHF implementation only use FSDP? At least given what I can find on the repository, it doesn't look like you use any 3D parallelism on your ChatGPT examples. 

Furthermore, we're pretty closely integrated with apex and nemo. We've been working with nvidia for quite a while now. Also, it looks like your RLHF implementation is not as mature as ours, lots of small regularization stuff that we've spend a long time resolving on TRLX (just look through our closed PRs for instance.) if folks on your team would add colossal as a backend to TRLX we would consider merging it. Adding a backend ourselves though would be a hundred thousand dollar endeavor with the engineering manpower we would need to hire to support it. I don't see FSDP being worth that price point.

**Comment by LouisCastricato** [comment]
We can schedule a call if you would prefer, email me @ louis@stability.ai
