### ISSUE TITLE
Cannot run PPO policy for summarization RLHF example 

### ISSUE THREAD

**Issue by double-orange** [CarperAI/trlx#384]
### 🐛 Describe the bug

![5c097e7552541d3cef5238a69e39acc](https://user-images.githubusercontent.com/58323790/226506004-381ead95-5ccb-4ae8-81aa-6991ce8b5c5b.jpg)

RuntimeError:exp _vml_cpu not implemented for Half

**Comment by reciprocated** [comment]
Should be resolved with https://github.com/CarperAI/trlx/pull/363, could you pull from the main and try again?

**Comment by arpitg1991** [comment]
i had the same issue, works after pulling latest

**Comment by double-orange** [comment]
The updated code solves this problem
