### ISSUE TITLE
ppo trained model and checkpoints are not accesible

### ISSUE THREAD

**Issue by arpitg1991** [CarperAI/trlx#385]
### 🐛 Describe the bug

when running `trlx_gptj_text_summarization.py` it doesnt save final model. Checkpoints saved also dont seem to load correctly. It complains that `pytorch_model.bin` is missing. Checkpoint folder looks like
total 48
```
-rw-rw-r-- 1 ec2-user ec2-user    13 Mar 22 17:16 latest
drwxrwxr-x 2 ec2-user ec2-user    89 Mar 22 17:16 pytorch_model
-rw-rw-r-- 1 ec2-user ec2-user 17683 Mar 22 17:16 random_states_0.pkl
-rw-rw-r-- 1 ec2-user ec2-user   627 Mar 22 17:16 scheduler.bin
-rwxrw-r-- 1 ec2-user ec2-user 18857 Mar 22 17:16 zero_to_fp32.py
```
`pytorch_model` directory has these:
```
total 816364
-rw-rw-r-- 1 ec2-user ec2-user 263920695 Mar 22 17:16 mp_rank_00_model_states.pt
-rw-rw-r-- 1 ec2-user ec2-user 572032601 Mar 22 17:16 zero_pp_rank_0_mp_rank_00_optim_states.pt

```

### Which trlX version are you using?

latest

### Additional system and package information

latest

**Comment by LouisCastricato** [comment]
@PhungVanDuy
