### ISSUE TITLE
support llama

### ISSUE THREAD

**Issue by akk-123** [CarperAI/trlx#389]
### 🚀 The feature, motivation, and pitch

please support llama

**Comment by LouisCastricato** [comment]
We already support llama. Please stop making issues about not relevant things.

**Comment by nikokaoja** [comment]
@LouisCastricato is this in anyway related to this PR:
https://github.com/CarperAI/trlx/pull/375

would with this PR trlx fully support LLAMA ?

**Comment by LouisCastricato** [comment]
Yes this pr would fully support llama, excluding nemo support as that would simply require you to write a checkpoint converter
