### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by chuckhope** [CarperAI/trlx#391]
### 🐛 Describe the bug

Hello, I would like to know if it is necessary to use a more recent version of CUDA, such as 1106, or if I can use an older version, such as CUDA 10.2?

### Which trlX version are you using?

0.5.0

**Comment by reciprocated** [comment]
Hi! Can't tell for certain if it's really necessary, however this library is only tested against the most recent versions of CUDA (11.8, 12.0) and pytorch (1.13, 2.0), so there might be some bumps when using older versions, yet I encourage you to just to try it and see if it works on you setup! :)
