### ISSUE TITLE
The question on the implementation details of ILQL

### ISSUE THREAD

**Issue by Yuanhy1997** [CarperAI/trlx#398]
### 🐛 Describe the bug

Hi, I am recently using trlx to implement ILQL algorithm. When I go through your codes, I found that trlx version of ILQL uses one single transformers model (GPT2) for both the policy model and the Q(value) function model, and there are just different heads to separate different functions. While in the ILQL paper, their implementation details said they used a supervise-trained transformer as the policy model and use a separate transformers model as Q(value) functions.  Although it might be a good way to same computational resources sharing one sole transformer with (or without) performance trade-off. I still wonder why you implement trlx ilql in such a way, it would be great if you can explain the ideas. BTW, we read the code corresponding to the ilql_sentiments.py in the example folder.

### Which trlX version are you using?

trlx== 0.5.0

**Comment by reciprocated** [comment]
Hey! You're correct, this particular implementation (which would be equivalent to `seperate_policy: false, seperate_target: false` in the original implementation https://github.com/Sea-Snell/Implicit-Language-Q-Learning/blob/4af8c5c12baf69c743dc9753e377a427109b7e93/config/toxicity/train_iql.yaml#L52), is as you've said both lighter on computational resources and is easier conceptually, however it might be more sensitive to hyperparameter tuning as Chalie Snell had previously pointed out from his experience. With that said separating policy and training value heads in isolation should be easy by setting `awac_scale` to `0`, while separating target head would still require inferring additional transformer body during training, which depending on its size could be undesirable. Yet I would still be interested at making a comparison here and determine whether it does or does not incur a performance trade-off.

**Comment by Yuanhy1997** [comment]
Really helpful responses! That would be an interesting engineering perspective whether sharing parameters or not.
