### ISSUE TITLE
PPO training stuck on `make_experience`

### ISSUE THREAD

**Issue by reciprocated** [CarperAI/trlx#399]
### 🐛 Describe the bug

The following script would get stuck indefinitely on the second rollout collection:
```python
import trlx
from trlx.data.default_configs import default_ppo_config

def main():
    config = default_ppo_config()
    config.train.seq_length = 1024
    config.model.model_path = "gpt2"
    config.method.gen_kwargs["top_k"] = 1

    prompts = ["*" * 256] * 1024

    trlx.train(
        reward_fn=lambda samples, **kwargs: [0] * len(samples),
        prompts=prompts,
        eval_prompts=prompts,
        config=config,
        stop_sequences=["*"],
    )

if __name__ == "__main__":
    main()
```
```bash
accelerate launch --num_processes 1 --config_file configs/accelerate/zero2-bf16.yaml examples/ppo_stuck.py
```

### Which trlX version are you using?

latest @ https://github.com/CarperAI/trlx/tree/114998b8171e7ce8d543b2102efe8a612a01ff9f

### Additional system and package information

from https://github.com/CarperAI/trlx/blob/114998b8171e7ce8d543b2102efe8a612a01ff9f/requirements.txt

**Comment by javirandor** [comment]
I am facing this same issue even with the updated code.

I am trying to reproduce the HH fine-tuning example on Alpaca.

```
trlx.train(
    prompts=prompts,
    eval_prompts=eval_prompts,
    reward_fn=reward_fn,
    config=config,
    stop_sequences=["Human:", "human:", "Assistant:", "assistant:"]
)
```

My code gets stuck generating the second batch of rollouts `16/64`.

I am running the code on a cluster with 8xA100s (80GB) and using a custom reward model. Providing a minimal reproducible example is a bit hard for my current setup. Do you have any pointers that can help me debug this issue?
