### ISSUE TITLE
AttributeError: module 'trlx' has no attribute 'train'

### ISSUE THREAD

**Issue by Myashka** [CarperAI/trlx#411]
### 🐛 Describe the bug

I am trying to start a train with PPO with my data according to https://github.com/CarperAI/trlx/tree/main/examples/summarize_rlhf example.

But after setting up all configs for this part of code
```
trainer = trlx.train(
    reward_fn=reward_fn,
    prompts=train_prompts,
    eval_prompts=val_prompts[0:1000],  # sampling 1000 validation prompts for evaluation speed in training
    config=config,
)
```
returns **AttributeError: module 'trlx' has no attribute 'train'**. I work in google colab with GPU accelarator, but it doesn't seems like problem. Can anyone help me?

Seems like when I import lib I import only a file
![image](https://user-images.githubusercontent.com/57448108/229361224-73901054-b578-4ad9-9323-e385a8857063.png)

### Which trlX version are you using?

-e git+https://github.com/CarperAI/trlx.git@b7db6f9e74c7d8dc719255b27968d2994836957a#egg=trlx

**Comment by PhungVanDuy** [comment]
You should install `trlx` instead of importing from directory:

```bash
git clone https://github.com/CarperAI/trlx.git
cd trlx
pip install torch==2.0.0 --extra-index-url https://download.pytorch.org/whl/cu116 # for cuda
pip install -e .
```
