### ISSUE TITLE
can padding_side be 'right'?

### ISSUE THREAD

**Issue by rockmagma02** [CarperAI/trlx#424]
### 🐛 Describe the bug

First off, I'd like to say that this is an excellent repo. 

However, I did notice that the default tokenizer config sets padding_side=left, which seems to be different from the common default of right in most NLP tokenizers. While I understand that setting padding_side to right might be more convenient when calculating advantages, I think it could potentially lead to bugs if users are allowed to modify it. Would it be safer to prevent users from modifying the padding side?

### Which trlX version are you using?

newest

**Comment by Chen9154** [comment]
@rockmagma02 For some frequently-used gpt-like LLMs such as BLOOM, the padding_side is set to left by default. Meanwhile, you could easily change the padding_side to right after initialization.

rw_tokenizer = AutoTokenizer.from_pretrained("bigscience/bloom-1b1")
rw_tokenizer.padding_side = 'right'
