### ISSUE TITLE
Running CUDA OOM with PPO on llama

### ISSUE THREAD

**Issue by TonyZhanghm** [CarperAI/trlx#431]
### 🐛 Describe the bug

Hi! I'm running ppo on llama-7B and some customized reward models. I was trying to increase `max_new_tokens` in gen_kwargs  to 512 and got cuda OOM on 8 A100s when during here https://github.com/CarperAI/trlx/blob/main/trlx/trainer/accelerate_ppo_trainer.py#L383 .
Any advices on saving CUDA memory? Some previous issues mentioned zero3 doesn't work well with PPO either.

### Which trlX version are you using?

master branch

**Comment by PhungVanDuy** [comment]
> ### 🐛 Describe the bug
> Hi! I'm running ppo on llama-7B and some customized reward models. I was trying to increase `max_new_tokens` in gen_kwargs to 512 and got cuda OOM on 8 A100s when during here https://github.com/CarperAI/trlx/blob/main/trlx/trainer/accelerate_ppo_trainer.py#L383 . Any advices on saving CUDA memory? Some previous issues mentioned zero3 doesn't work well with PPO either.
> 
> ### Which trlX version are you using?
> master branch
> 
> ### Additional system and package information
> _No response_

Did you try to run with zero offload and fp16? It would be great if you can share your settings (trlx config, accelerate config)
