### ISSUE TITLE
Training the reward model on a summarization dataset resulted in a mismatch between the training accuracy and the actual performance during use

### ISSUE THREAD

**Issue by Bo396543018** [CarperAI/trlx#442]
### 🐛 Describe the bug

When calculating accuracy scores during training, they are based on the maximum index of pairs, while in actual use there is only a single sentence. This may not align the performance during actual inference with that during training. Is this reasonable?

**Comment by tjlujianqiao** [comment]
one more question is, using the configuration in train_reward_model_gptj.py, we can not reproduce the eval_loss curve, do you have the same problems?

**Comment by Bo396543018** [comment]
> one more question is, using the configuration in train_reward_model_gptj.py, we can not reproduce the eval_loss curve, do you have the same problems?

I did not train GPT-J myself, and the accuracy and logs from previous training by other people generally match up.
