### ISSUE TITLE
make experience in accelerate_ppo_trainer

### ISSUE THREAD

**Issue by weizhenzhao** [CarperAI/trlx#445]
### 🐛 Describe the bug

``<img width="1438" alt="image" src="https://user-images.githubusercontent.com/13706689/233752423-6d05d859-bb13-4cb8-9941-39be1c8dc534.png">
in ppotrainer I find that the reward_fn pass three parameters

- all_str_samples
- prompts            
- all_str_outputs            

what does these three parameters means by?
I found that in the definition of reward model in ppo_hh.py
``` python

        def reward_fn(samples, prompts, original_output, **kwargs):
            samples = [s + reward_tokenizer.eos_token for s in samples]
            rewards = get_reward(samples)

            if not delta_reward:
                return rewards

            original_samples = [p + o + reward_tokenizer.eos_token for p, o in zip(prompts, original_output)]
            original_rewards = get_reward(original_samples)
            return rewards - original_rewards

```

samples : is the generated text of critic model
prompts:  is the input text for generating
original_output : is the standard text written by human

but in the method of make_experience in accelerate_ppo_trainer.py
how can I found the last one ? 
"original_output : is the standard text written by human"

### Which trlX version are you using?

latest

**Comment by reciprocated** [comment]
Hey, you are correct about all of these, `original_output` comes from the `metadata` which can be extended with arbitrary keywords (see #301, #423 for motivation). In that example it is injected here: https://github.com/CarperAI/trlx/blob/6e655a4a1194eac76d00643c4b5fa56a07384c43/examples/hh/ppo_hh.py#L212-L213
