### ISSUE TITLE
Does RLHF part supports multi-node training?

### ISSUE THREAD

**Issue by Chevolier** [CarperAI/trlx#446]
### 🚀 The feature, motivation, and pitch

It seems that the RLHF part cannot support training using multi-nodes, can you support it?

**Comment by reciprocated** [comment]
Yes it does! trlX supports multi-node training either through [🤗 Accelerate](https://huggingface.co/docs/accelerate/) or [NVIDIA NeMo](https://github.com/NVIDIA/NeMo) backends. Consider browsing through these scripts (https://github.com/CarperAI/trlx/blob/main/scripts/slurm_train.sh) and also through (https://github.com/CarperAI/trlx/tree/main/trlx/models#nemo-megatron-setup) for setting up the respective backends.
