### ISSUE TITLE
tokenizer of the summarization rlhf example

### ISSUE THREAD

**Issue by DanqingZ** [CarperAI/trlx#466]
### 🐛 Describe the bug

In tokenizer config, we set the tokenizer as GPT2 in: https://github.com/CarperAI/trlx/blob/main/examples/summarize_rlhf/trlx_gptj_text_summarization.py#L46

why are we using GPT2 tokenizer here, why not "EleutherAI/gpt-j-6B"? I loaded and checked that GPT2 and GPTJ tokenizers are mostly the same. But I am wondering why we deliberately use GPT2 tokenizer here. Thanks!

**Comment by reciprocated** [comment]
Hello @DanqingZ, the difference here is superficial, since as you mentioned these are same tokenizers. But if you think that's confusing, please open a PR and change it! Because there was slightly different but a similar issue before #325
