### ISSUE TITLE
How to use checkpoint?

### ISSUE THREAD

**Issue by mshtelma** [CarperAI/trlx#480]
### 🐛 Describe the bug

I am following a PPO example using the HH dataset: https://github.com/CarperAI/trlx/blob/main/examples/hh/ppo_hh.py
My training is running, and I have a best_checkpoint. Do you know how I can use it? 
I have tried so far the following recipe described in one of the [issues](https://github.com/CarperAI/trlx/issues/365), but it does not work for me:

```
import torch
from trlx.models.modeling_ppo import AutoModelForCausalLMWithValueHead
model = AutoModelForCausalLMWithValueHead.from_pretrained("...")
model.load_state_dict(torch.load("/...../best_checkpoint/pytorch_model/mp_rank_00_model_states.pt")["module"])
```

What would be the correct approach for loading the checkpoint and converting it to the hugging face model?

### Which trlX version are you using?

master

**Comment by glerzing** [comment]
I'm not an expert, but if you just want to use the model, without retraining, doesn't it work if you just do 
``` Python
model = AutoModelForCausalLMWithValueHead.from_pretrained("/...../best_checkpoint")
```
If you just want to use the model for inference, the important file in the directory is "pytorch_model.bin", and `from_pretrained` will automatically load it.

If you needed the checkpoint for retraining, that would be more something like:
``` Python
trainer = AcceleratePPOTrainer(....)
trainer.load(checkpoint_dir)
trainer.learn()
```

**Comment by Dahoas** [comment]
@mshtelma Any update on this? Any @glerzing describes you should just be able to load the saved model via `AutoModelForCausalLMWithValueHead.from_pretrained`for inference.

**Comment by maxreciprocate** [comment]
@glerzing's response was complete. Currently to load the model for inference you have to do:
```python
# for PPO and SFT
from transformers import AutoModel
model = AutoModel.from_pretrained("ckpts/best_checkpoint/hf_model")

# for ILQL
from trlx.models.modeling_ilql import AutoModelForCausalLMWithILQLHeads
model = AutoModelForCausalLMWithILQLHeads.from_pretrained("ckpts/checkpoint_t/hf_model")
```
