### ISSUE TITLE
Implements beam search of AutoModelForCausalLMWithILQLHeads

### ISSUE THREAD

**Issue by zwhe99** [CarperAI/trlx#484]
### 🚀 The feature, motivation, and pitch

I notice that AutoModelForCausalLMWithILQLHeads has its own generate function, which only supports sampling. Would it be possible to use beam search?

**Comment by Dahoas** [comment]
We definitely agree this would be a useful addition, however there are other features we are prioritising right now. It would be a nice pr if you feel like addressing this yourself!
