### ISSUE TITLE
Getting Started As a Domain Expert

### ISSUE THREAD

**Issue by fredzannarbor** [CarperAI/trlx#49]
### 🚀 The feature, motivation, and pitch

Getting Started Guide for Domain Experts

A step-by-step cookbook that enables people with domain knowledge to rapidly begin contributing (and receiving) value to the open-source RLHF project.

Motivation: I am able to install tlrx and am confident that I will be able to get component scripts running. However, I do not have a clear path to doing something that is quickly useful to me and to others.

Goal: 

I would like to be able to pick a particular domain that I am expert in--for example, book publishing, military history, climate change--and provide "human feedback" that visibly makes results better for a) me on a toy setup b) everyoe when deployed

Suggested approach:

Step-by-step guide with sample artifacts.

### Alternatives

I might have taken this to Discord, but I hate Discord. It is noisy and chaotic. Github is much better suited for domain expertise projects.

### Additional context

Glad to help.

**Comment by LouisCastricato** [comment]
Hey! We're working on such a guide right now. It's just a bit slow going. Don't worry. In the meantime, I'd recommend reading some papers outlined here:

https://www.notion.so/carperai/RL-Reading-Group-91c38c82022e4b84b203493d58abde41

**Comment by fredzannarbor** [comment]
Great! How can I join the Reading Group? the seminars sound fun.

**Comment by LouisCastricato** [comment]
Join the discord and I can tag you

**Comment by LouisCastricato** [comment]
https://github.com/CarperAI/trlx/issues/65 Duplicate issue. Closing this issue since folks are already assigned to the other one.
