### ISSUE TITLE
My loss graph seems weird. (PPO training)

### ISSUE THREAD

**Issue by sooftware** [CarperAI/trlx#491]
- Loss graph
<img width="1846" alt="image" src="https://github.com/CarperAI/trlx/assets/42150335/7653e5f0-7cf4-43d8-b426-26b33ca88dee">

I'm trying to train 'examples/summarization_rlhf' by changing the dataset a little bit, (the Reward Model trained well I think), but the Step-3 PPO Training graph is as above.  
  
Can policy losses have a negative value?  
 
And are there any expected problems?

**Comment by sooftware** [comment]
## My dataset format

- Prompt
```
Blah, blah, blah<|sep|>A:Blah, blah, blah.<|sep|>B:
```

- Answer
```
Blah, blah, blah.
```

**Comment by sooftware** [comment]
- Reward graph
<img width="621" alt="image" src="https://github.com/CarperAI/trlx/assets/42150335/b65895dd-72c7-4816-a89a-175c53c1c9a8">

**Comment by sooftware** [comment]
Is it because the Reward average is negative?

**Comment by Dahoas** [comment]
If the reward is not normalized than rewards can (and often will) be negative. Can you share your hyperparameters/setup?

**Comment by sooftware** [comment]
A normal loss graph gradually drops to a curve, is this PPO loss graph normal? Or is that graph weird?

**Comment by sooftware** [comment]
Thank you!
