### ISSUE TITLE
Type hint doesn't match documentation for prompts arg of PromptPipeline.__init__

### ISSUE THREAD

**Issue by g-simmons** [CarperAI/trlx#494]
https://github.com/CarperAI/trlx/blob/0dce99d96b7d70b6a9114129d8e38bf6c80eb653/trlx/pipeline/offline_pipeline.py#L108-L116

https://github.com/CarperAI/trlx/blob/0dce99d96b7d70b6a9114129d8e38bf6c80eb653/trlx/pipeline/offline_pipeline.py#L126

**Comment by LouisCastricato** [comment]
would be an easy PR if you wanna fix it ;)
