### ISSUE TITLE
Add support for LLaMA2

### ISSUE THREAD

**Issue by cvetanovskaa** [CarperAI/trlx#533]
### 🚀 The feature, motivation, and pitch

As Meta released LLaMA2 yesterday, and it's already on huggingface: https://huggingface.co/meta-llama, it would be great to make this library support it.

**Comment by PhungVanDuy** [comment]
LLaMA 2 is compatible with the current code based:

e.g. https://wandb.ai/pvduy/trlx/runs/04m8pfvy
