### ISSUE TITLE
trlx has no attribute 'train'

### ISSUE THREAD

**Issue by alat-rights** [CarperAI/trlx#58]
### 🐛 Describe the bug

Trying to run a train loop with trlx

Erroring with trlx has no attribute train

Code being ran (from README):
```
import trlx

# optimize some reward function
model = trlx.train('gpt2', reward_fn=lambda samples: [sample.count('cats') for sample in samples])

# or steer a model with a collection of rated samples
model = trlx.train('EleutherAI/gpt-j-6B', dataset=[('dolphins', 'geese'), (1.0, 100.0)])

# model is a wrapper with some logit preprocessing
model.generate(**tokenizer('Q: Who rules the world? A:', return_tensors='pt'), do_sample=True)
```

Behavior:
```
  File "/home/[user]/trlx/main.py", line 4, in <module>
    model = trlx.train('gpt2', reward_fn=lambda samples: [sample.count('cats') for sample in samples])
AttributeError: module 'trlx' has no attribute 'train'
```

### Which trlX version are you using?

master

### Additional system and package information

OpenSUSE + Python 3.10.7

**Comment by alat-rights** [comment]
Untarred the v0.2 release, and did not encounter the same error there. Curious.

**Comment by LouisCastricato** [comment]
Cannot repro. Talked with @alat-rights on discord. Closing issue. Will reopen if others report similar problems.

**Comment by farhad-abdi** [comment]
I'm facing the same problem on colab

**Comment by LouisCastricato** [comment]
trlx is not designed for colab usage. iirc there is an available colab notebook floating around the open assistant discord server. This notebook is not officially endorsed. https://colab.research.google.com/drive/11CTcGVXYK6XLN8KpulcEkehTA1Au8f2o?usp=sharing

**Comment by farhad-abdi** [comment]
Thank you, would you be able to outline conflicts and problems for using in colab, maybe I can resolve them!

**Comment by LouisCastricato** [comment]
It works in colab but colab is not a platform that we actively go out of our way to support. TRLX is designed for super computers. it would be the equivalent of trying to get Megatron or NeoX working in colab. I am sure you could do it with enough effort, but I don't see the use case.

**Comment by LouisCastricato** [comment]
If you use the colab notebook above, for instance, there is no multinode or multigpu support since trlx's accelerate implementation tends to not play nicely with colab. You can use colab fine for single gpu stuff *at the moment.*.

**Comment by farhad-abdi** [comment]
You are right, unfortunately this notebook also would not rum on colab.

**Comment by LouisCastricato** [comment]
You probably have some installation issue. I just checked the notebook and it runs. Make sure to restart the colab after you install the package.
