### ISSUE TITLE
What deepspeed config was this tested on?

### ISSUE THREAD

**Issue by Breakend** [CarperAI/trlx#59]
### 📚 The doc issue

There is no information on what config or machines this was tested on, nor what the results actually were. I was unable to get my configuration to work for the example code, but I might be using an untested deepspeed configuration (e.g., stage 3 offloading). I'd like to test with the validated configuration.

### Suggest a potential alternative/fix

Could you add the tested configurations and machines? Thanks!

**Comment by LouisCastricato** [comment]
@reciprocated and @Dahoas have the deepspeed configuration. Will have it merged. We usually use stage 2 though.

**Comment by LouisCastricato** [comment]
https://github.com/CarperAI/trlx/issues/34#issuecomment-1286363960 This accelerate config works. Typically we don't use custom deepspeed configurations unless multinode is required.

**Comment by LouisCastricato** [comment]
Resolved?

**Comment by promiseve** [comment]
Can the discord link be posted here?

**Comment by LouisCastricato** [comment]
https://discord.gg/canadagoose

**Comment by promiseve** [comment]
Thanks, joined.
