### ISSUE TITLE
Stale configs for `ppo_gptj.yml`

### ISSUE THREAD

**Issue by jon-tow** [CarperAI/trlx#66]
### 🐛 Describe the bug

The `ppo_gptj.yml` [config](https://github.com/CarperAI/trlx/blob/master/configs/ppo_gptj.yml) is currently out of date from recent updates.

- `n_ctx`, `grad_clip`, `log_interval`, `input_size`, `gen_size`, `accelerate`, `accelerate_config_path` are not fields of `TrainConfig` and should be removed. 
- `device` is not a field of `ModelConfig` and should be removed.

Do we want this config or should it be removed as it's mostly a duplicate of `ppo_config.yml` [here](https://github.com/CarperAI/trlx/blob/master/configs/ppo_config.yml) with a model path change.

### Which trlX version are you using?

trlx==0.2.0

**Comment by LouisCastricato** [comment]
Do you mind updating this yourself 😅
