### ISSUE TITLE
Python 3.7 support (for Colab)

### ISSUE THREAD

**Issue by honglu2875** [CarperAI/trlx#67]
### 🐛 Describe the bug

In Colab running `!pip install git+https://github.com/CarperAI/trlx` resulted in
```
ERROR: No matching distribution found for numpy>=1.23.2
```

Numpy did drop support in recent releases for Python 3.7 which is what Google Colab is using right now. One might consider downgrade numpy. Per discussions in Discord I put it here so that we don't forget.

### Additional system and package information

numpy==1.23.2

**Comment by thedch** [comment]
It's worth noting that other parts of the repo do not work with 3.7, such as magic f-strings. Is there a meaningful usecase for Colab support?
