### ISSUE TITLE
Support for RLHF tuned Seq2Seq models

### ISSUE THREAD

**Issue by VenkateshDas** [CarperAI/trlx#68]
### 🚀 The feature, motivation, and pitch

Trlx repo supports decoder-only models such as GPT2, GPTJ etc. It will be beneficial to implement an Encoder-Decoder model for RLHF finetuning.
Providing an implementation that supports Encoder-Decoder models will be beneficial as they are also widely used in many NLP downstream tasks.
It will be good to have T5 as a base model for the Encoder-Decoder arch.

**Comment by danyang-rainbow** [comment]
+1, hoping that T5 will be supported soon~

**Comment by shermansiu** [comment]
May need this for a course project. Will likely work on this soon.

**Comment by shermansiu** [comment]
Looking at the code, it's relatively simple to implement... The code may need to be refactored to ensure that code isn't repeated unnecessarily though ([DRY](https://www.digitalocean.com/community/tutorials/what-is-dry-development)).

**Comment by VenkateshDas** [comment]
That's good to hear @shermansiu . I agree refactoring has to be done to the existing code base. The initial setup for T5 model can be just the decoder part. Will be happy to collaborate too.
