### ISSUE TITLE
Create a unified API between PPO and ILQL

### ISSUE THREAD

**Issue by LouisCastricato** [CarperAI/trlx#7]
Currently ILQL was implemented more or less in a vacuum of our PPO implementation. As such, ILQL has features that our PPO implementation needs. This includes

- Removing the dependency on GPT2 for PPO. This is currently being done [here](https://github.com/samp830/trlx), but we can create a more standardized approach
- Adding the ability to pass custom reward functions to the orchestrator. This is an absolute must have.
- Standardized naming conventions between functions.

**Comment by LouisCastricato** [comment]
@reciprocated @Dahoas no rush on this but whenever you guys get a chance we should discuss this in this issue.

**Comment by LouisCastricato** [comment]
Fixed the first point with #11 

All that remains is standardizing naming conventions.

**Comment by reciprocated** [comment]
On the topic of unified api, to encourage new users I vote for simplifying down to

```python
import trlx
# for ppo
trlx.train(model_path, reward_fn)
# for ilql
trlx.train(model_path, samples, ratings)
```

**Comment by LouisCastricato** [comment]
I like that, good idea
