### ISSUE TITLE
Amos optimizer support

### ISSUE THREAD

**Issue by LouisCastricato** [CarperAI/trlx#72]
### 🚀 The feature, motivation, and pitch

https://arxiv.org/abs/2210.11693

Amos reports better scaling (for multi accelerator) and better performance when compared to AdamW for autoregressive and masked language modeling. We should apply it to trlX and see if it helps speed up RLHF.

### Alternatives

We could alternatively just stay with AdamW, which is very tried and tested.

### Additional context

We need to seriously consider the wall time constraints of Amos and if it creates any serious optimization bottlenecks for us.

**Comment by VijayKalmath** [comment]
@LouisCastricato Would like to work on this. Will try to work on it over the weekend but might need some guidance.

**Comment by Dahoas** [comment]
Let us know if you run into any issues here or on the trlx channel.

**Comment by LouisCastricato** [comment]
Following up

**Comment by LouisCastricato** [comment]
Closing issue as inactivate.
