### ISSUE TITLE
Example/Test Model Benchmarks (Canonical WandB runs)

### ISSUE THREAD

**Issue by cat-state** [CarperAI/trlx#74]
### 🚀 The feature, motivation, and pitch

If we had links to benchmarks for the example (and/or test) models, it would be easier to add new models, and keep track of improvements in method implementations. Additionally, during refactoring, it would allow checking that no performance degrading changes were introduced.

This can be a minimal version of https://github.com/CarperAI/trlx/issues/13

**Comment by albertsun1** [comment]
Hey! I'm new to contributing to trlx, would it be worth for me to give this a go for the ppo/ilql sentiment examples?

**Comment by cat-state** [comment]
> Hey! I'm new to contributing to trlx, would it be worth for me to give this a go for the ppo/ilql sentiment examples?
Sure, although you might need compute?
@reciprocated maybe we should make a single-node config version that can be finetuned on a single gpu fast?

**Comment by cat-state** [comment]
So I see that WandB actually lists the commit hash used for a run. So if we could find/tag TRLX runs appropriately then each commit could be matched up to a specific state of the repository.

**Comment by reciprocated** [comment]
> Sure, although you might need compute? @reciprocated maybe we should make a single-node config version that can be finetuned on a single gpu fast?

{ppo,ilql}_config.yml were meant to be single gpu, up to a batch_size, since they both use gpt2 small

**Comment by maxreciprocate** [comment]
Resolved with https://github.com/CarperAI/trlx/pull/357
